name: Mark stale issues and pull requests

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight
  workflow_dispatch:

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v10
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: |
            This issue has been automatically marked as stale because it has not had
            recent activity. It will be closed if no further activity occurs within 7 days.
            Thank you for your contributions.
          stale-pr-message: |
            This pull request has been automatically marked as stale because it has not had
            recent activity. It will be closed if no further activity occurs within 7 days.
            Thank you for your contributions.
          close-issue-message: |
            This issue has been automatically closed due to inactivity.
            If you believe this is still relevant, please reopen it or create a new issue.
          close-pr-message: |
            This pull request has been automatically closed due to inactivity.
            If you believe this is still relevant, please reopen it or create a new pull request.
          days-before-stale: 60
          days-before-close: 7
          stale-issue-label: 'stale'
          stale-pr-label: 'stale'
          exempt-issue-labels: 'pinned,security,good first issue'
          exempt-pr-labels: 'pinned,security'
          operations-per-run: 50